/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ['class'],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-surface': '#1c1b1b',
        'on-error-container': '#93000a',
        'on-tertiary-fixed-variant': '#484645',
        'on-background': '#1c1b1b',
        'inverse-on-surface': '#f4f0ef',
        'surface-variant': '#e5e2e1',
        'on-tertiary': '#ffffff',
        secondary: '#625e59',
        'error-container': '#ffdad6',
        'inverse-surface': '#313030',
        'inverse-primary': '#c8c6c5',
        outline: '#747878',
        'on-secondary-fixed-variant': '#4a4642',
        background: '#fdf8f8',
        'tertiary-fixed-dim': '#cac6c4',
        'primary-container': '#1c1b1b',
        'on-primary-fixed-variant': '#474746',
        'surface-dim': '#ddd9d8',
        'secondary-container': '#e5dfd8',
        'surface-container-highest': '#e5e2e1',
        'on-secondary-container': '#66625d',
        'tertiary-fixed': '#e6e2df',
        error: '#ba1a1a',
        'outline-variant': '#c4c7c7',
        'surface-container': '#f1edec',
        'primary-fixed': '#e5e2e1',
        'on-tertiary-fixed': '#1c1b1a',
        'on-primary-fixed': '#1c1b1b',
        'surface-bright': '#fdf8f8',
        'surface-container-lowest': '#ffffff',
        'secondary-fixed-dim': '#ccc5bf',
        'on-secondary-fixed': '#1e1b17',
        surface: '#fdf8f8',
        'on-surface-variant': '#444748',
        'on-tertiary-container': '#868382',
        'on-error': '#ffffff',
        'secondary-fixed': '#e8e1db',
        'on-secondary': '#ffffff',
        'surface-tint': '#5f5e5e',
        'on-primary-container': '#858383',
        primary: '#000000',
        'surface-container-high': '#ebe7e6',
        tertiary: '#000000',
        'primary-fixed-dim': '#c8c6c5',
        'surface-container-low': '#f7f3f2',
        'tertiary-container': '#1c1b1a',
        'on-primary': '#ffffff',
        sage: '#E2E8DF',
        'sage-deep': '#E2E8CE',
        blush: '#F4E4E4',
        'blush-deep': '#F8D7DA',
        butter: '#FDF3E1',
        'butter-deep': '#FFF3CD',
        lavender: '#E6E6FA',
        border: '#e5e2e1',
        input: '#e5e2e1',
        ring: '#1c1b1b',
        foreground: '#1c1b1b',
        card: { DEFAULT: '#ffffff', foreground: '#1c1b1b' },
        popover: { DEFAULT: '#ffffff', foreground: '#1c1b1b' },
        destructive: { DEFAULT: '#ba1a1a', foreground: '#ffffff' },
        muted: { DEFAULT: '#f1edec', foreground: '#444748' },
        accent: { DEFAULT: '#e5dfd8', foreground: '#1c1b1b' },
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '1rem',
        md: '0.75rem',
        sm: '0.25rem',
        xl: '1.5rem',
        full: '9999px',
        card: '32px',
        panel: '24px',
      },
      spacing: {
        unit: '8px',
        'container-padding': '40px',
        'sidebar-width': '80px',
        gutter: '24px',
        'card-gap': '24px',
        'section-margin': '80px',
      },
      fontFamily: {
        'body-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'label-caps': ['Hanken Grotesk', 'sans-serif'],
        'body-md': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-lg': ['Hanken Grotesk', 'sans-serif'],
        'headline-lg-mobile': ['Hanken Grotesk', 'sans-serif'],
        'headline-md': ['Hanken Grotesk', 'sans-serif'],
        'headline-xl': ['Hanken Grotesk', 'sans-serif'],
        metadata: ['Plus Jakarta Sans', 'sans-serif'],
        sans: ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        'body-lg': ['18px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1.0', letterSpacing: '0.1em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
        'headline-lg': ['40px', { lineHeight: '1.1', letterSpacing: '-0.03em', fontWeight: '700' }],
        'headline-lg-mobile': ['32px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-xl': ['64px', { lineHeight: '1.0', letterSpacing: '-0.04em', fontWeight: '800' }],
        metadata: ['14px', { lineHeight: '1.4', letterSpacing: '0', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
};
